name: Pull Requests CI

on:
  pull_request:
    branches:
      - master
      - stable

jobs:
  build_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci --production=false
      - name: Transpile code
        run: npm run build
      - name: Run unit tests
        run: npm run test
